{
 "title": "Guppy's Dashboard - GIT Version",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Guppy's Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Portfolio Balance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "BTC" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(checked) as time_sec,\n  value as value,\n  \"Portfolio Value\" as metric\nFROM portfolio_history\nORDER BY time_sec ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(checked) as time_sec,\n  ethValue as value,\n  \"G50 Token Value\" as metric\nFROM portfolio_history\nORDER BY time_sec ASC\n\n"
    }
   ]
  },
  {
   "title": "Current Holdings",
   "type": "table",
   "description": "The current list of coins that Guppy is holding. Dust coins are excluded from this list.",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n     coin as \"Coin\", qty as \"Qty\", btc_value as \"BTC Equiv\"\r\nFROM\r\n     binance_holdings\r\nWHERE\r\n     btc_value > 0.008\r\nORDER BY\r\n     coin ASC"
    }
   ]
  },
  {
   "title": "Current DCA Log",
   "type": "table",
   "description": "Current HODL Bags",
   "gridPos": { "h": 12, "w": 16, "x": 4, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT market as \"Coin\", boughtTimes as \"DCA Level\", profit as \"Gain/Loss\", avg_avgPrice as \"Avg Price\", avg_avgCost as \"Avg Cost\", age as \"Days in DCA\", currentPrice as \"Current Price\", sellStrategy as \"Sell Strategy\", triggerValue as \"Profit Sell Trigger\", percChange as \"Daily Change\" from pt_dcaLogData"
    }
   ]
  },
  {
   "title": "Profit Today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM((currentPrice * soldAmount * 0.998) - (avg_avgPrice * soldAmount))\nFROM pt_sellLogData\nWHERE DATE(CONVERT_TZ(soldDate,'+00:00', '+10:00')) = CURDATE()"
    }
   ]
  },
  {
   "title": "Profit Yesterday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM((currentPrice * soldAmount * 0.998) - (avg_avgPrice * soldAmount))\nFROM pt_sellLogData\nWHERE DATE(CONVERT_TZ(soldDate,'+00:00', '+10:00')) = CURDATE() - INTERVAL 1 DAY"
    }
   ]
  },
  {
   "title": "Profit Last 7 days",
   "type": "singlestat",
   "description": "Running 7-day summary",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM((currentPrice * soldAmount * 0.998) - (avg_avgPrice * soldAmount))\nFROM pt_sellLogData\nWHERE DATE(CONVERT_TZ(soldDate,'+00:00', '+10:00')) >= CURDATE() - INTERVAL 7 DAY"
    }
   ]
  },
  {
   "title": "Profit All Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM((currentPrice * soldAmount * 0.998) - (avg_avgPrice * soldAmount))\nFROM pt_sellLogData\n"
    }
   ]
  },
  {
   "title": "Sell History",
   "type": "table",
   "description": "History of bot sells",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT soldDate as \"Sold\", market as \"Coin\", soldAmount as \"Qty\", boughtTimes as \"DCA Level\", Profit, avg_avgPrice as \"Avg Price\", avg_avgCost as \"Avg Cost\", avg_firstBoughtDate as \"First Bought\", currentPrice as \"Sell Price\", sellStrategy as \"Sell Strategy\", triggerValue as \"Sell Trigger\", avg_fee as \"Fee\" from pt_sellLogData"
    }
   ]
  },
  {
   "title": "Support this Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "content": "This is a dashboard I have created for my own little crypto bot community. I've made it available for all to use for free on your own bots.\n\nIf you find this dashboard useful, feel free to shout me a coffee:  \nBTC: 13QHePrFtKPY2axwRLVjEM6AjbbRvDSmP6  \nETH: 0x61a11050DC156CBA3ec49B81FC4F368FBd112059\n\n"
  }
 ]
}